# Site Settings

paginate:            5
disqus:              #"your-disqus"
repository:          theokyr/theokyr.github.io
github: [metadata]

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
