title:  Theo Kyriazidis
tagline:  Thessaloniki, Greece
author:
  name: "Theo Kyriazidis"
  twitter:  

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/theokyr'}
- {icon: 'instagram', link: 'https://instagram.com/theo.kyr'}
- {icon: 'envelope', link: 'mailto:theo.kyrr@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
