title:  Theo Kyriazidis
tagline:  Programmer based in Thessaloniki, Greece
author:
  name: "Theo Kyriazidis"
  twitter:  

menu:
- {name: 'Home', url: '../'}
- {name: 'Projects', url: '../projects/'}
- {name: 'Blog', url: '../blog/'}

social:
- {icon: 'github', link: 'https://www.github.com/theokyr'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/theo-kyriazidis-80022513b/'}
- {icon: 'instagram', link: 'https://instagram.com/theo.kyr'}
- {icon: 'envelope', link: 'mailto:theo.kyrr@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
